/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package HCache

/// type int-> 'I', long-> 'L', float-> 'F', double-> 'D', boolean-> 'B', string-> 'S', objectString-> 'OS', None-> 'N'
enum class CacheType(val flag: String) {
    INT("I"),
    LONG("L"),
    FLOAT("F"),
    DOUBLE("D"),
    BOOLEAN("B"),
    STRING("S"),
    OBJECT_STRING("OS"),
    NULL("N")
}

data class CacheValue(
    val type: String = CacheType.NULL.flag,
    val boolValue: Boolean = false,
    val intValue: Int = 0,
    val longValue: Long = 0,
    val floatValue: Float = 0.0F,
    val doubleValue: Double = 0.0,
    val stringValue: String = "",
)

fun CacheValue.isBoolean(): Boolean {
    return this.type == CacheType.BOOLEAN.flag
}
fun CacheValue.isInt(): Boolean {
    return this.type == CacheType.INT.flag
}
fun CacheValue.isLong(): Boolean {
    return this.type == CacheType.LONG.flag
}
fun CacheValue.isFloat(): Boolean {
    return this.type == CacheType.FLOAT.flag
}
fun CacheValue.isDouble(): Boolean {
    return this.type == CacheType.DOUBLE.flag
}
fun CacheValue.isString(): Boolean {
    return this.type == CacheType.STRING.flag
}
fun CacheValue.isStringObject(): Boolean {
    return this.type == CacheType.OBJECT_STRING.flag
}
fun CacheValue.isNull(): Boolean {
    return this.type == CacheType.NULL.flag
}

fun CacheValue.getBoolean(): Boolean? {
    return if (this.isBoolean()) {
        this.boolValue
    } else {
        null
    }
}

fun CacheValue.getInt(): Int? {
    return if (this.isInt()) {
        this.intValue
    } else {
        null
    }
}

fun CacheValue.getLong(): Long? {
    return if (this.isLong()) {
        this.longValue
    } else {
        null
    }
}

fun CacheValue.getFloat(): Float? {
    return if (this.isFloat()) {
        this.floatValue
    } else {
        null
    }
}

fun CacheValue.getDouble(): Double? {
    return if (this.isDouble()) {
        this.doubleValue
    } else {
        null
    }
}

fun CacheValue.getString(): String? {
    return if (this.isString()) {
        this.stringValue
    } else {
        null
    }
}

fun CacheValue.getStringObject(): String? {
    return if (this.isStringObject()) {
        this.stringValue
    } else {
        null
    }
}


class HCacheAndroid(val path: String) {
    init {
        System.loadLibrary("HCache")
        System.loadLibrary("HCacheAndroid")
    }

    fun get(key: String): CacheValue {
        val value = CacheValue()
        this.get(key, value)
        return value
    }

    external fun initKv(): Boolean
    private external fun get(key: String, value: CacheValue): Boolean
    external fun setBoolean(key: String, value: Boolean): Boolean
    external fun setInt(key: String, value: Int): Boolean
    external fun setLong(key: String, value: Long): Boolean
    external fun setFloat(key: String, value: Float): Boolean
    external fun setDouble(key: String, value: Double): Boolean
    external fun setString(key: String, value: String): Boolean
    external fun setObjectString(key: String, value: String): Boolean
}
